### ISSUE TITLE
Authorized ssh-rsa keys are exposed

### ISSUE THREAD

**Issue by zakufish** [UNSWComputing/rUNSWift-2016-release#1]
The **authorized_keys** file which contains the **authorized ssh-rsa keys of each user** can be seen by everyone in this repository (under the **/image/home/nao/.ssh/authorized_keys** directory), and it has been there for more than 11 months.
I am not too sure if this repository is still being used. Either way, it is a bad practice, and you should delete the entire repository as only deleting the file itself will still result in leaving the traces in your commit histories.

**Comment by jcol2** [comment]
These are public keys.

**Comment by zakufish** [comment]
That was a fast reply. Hah... no issue then.
Thanks 👍
